/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul9_pbo;

import java.util.Set;

/**
 *
 * @author Iin Nuraini
 */
public class pemilihandokter extends javax.swing.JFrame {

    /**
     * Creates new form pemilihandokter
     */
    public pemilihandokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        goldar = new javax.swing.JTextField();
        negara = new javax.swing.JTextField();
        praktik = new javax.swing.JTextField();
        spesialis = new javax.swing.JTextField();
        jconadokt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 10, 170, 30);

        jLabel2.setText("Dokter Spesialis");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 450, 120, 14);

        jLabel3.setText("Pilih Dokter");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 50, 90, 20);

        jLabel4.setText("Identitas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 70, 80, 20);

        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 100, 80, 20);

        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 140, 90, 20);

        jLabel7.setText("Usia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 180, 70, 14);

        jLabel8.setText("Jenis Kelamin");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 220, 100, 20);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(220, 100, 180, 30);
        getContentPane().add(alamat);
        alamat.setBounds(220, 140, 180, 30);
        getContentPane().add(usia);
        usia.setBounds(220, 180, 180, 30);
        getContentPane().add(jk);
        jk.setBounds(220, 220, 180, 30);

        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status);
        status.setBounds(220, 310, 180, 30);

        jLabel9.setText("Golongan Darah");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 270, 120, 14);

        jLabel10.setText("Status");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 310, 120, 14);

        jLabel11.setText("Kewarganegaraan");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 360, 120, 14);

        jLabel12.setText("Waktu Praktik");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 400, 120, 14);
        getContentPane().add(goldar);
        goldar.setBounds(220, 260, 180, 30);
        getContentPane().add(negara);
        negara.setBounds(220, 350, 180, 30);
        getContentPane().add(praktik);
        praktik.setBounds(220, 390, 180, 30);
        getContentPane().add(spesialis);
        spesialis.setBounds(220, 440, 180, 30);

        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "DR. Farras Yassar", "DR. Anisa Putri", "DR. Harun Fajar" }));
        jconadokt.setName(""); // NOI18N
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(150, 50, 170, 30);
        jconadokt.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed
         if(jconadokt.getSelectedItem().equals("DR. Farras Yassar")){
         
             nama.setText("DR. Farras Yassar");
             alamat.setText("Jl. Surabaya 16, Malang");
             usia. setText("20 Tahun");
             jk.setText("Laki-laki");
             goldar.setText("A");
             status.setText("Belum Menikah");
             negara.setText("Indonesia");
             praktik.setText("Pagi (07.00-15.00)");
             spesialis.setText("Dokter Umum");
            
         }
         else
         if(jconadokt.getSelectedItem().equals("DR. Anisa Putri")){
             nama.setText("DR. Anisa Putri");
             alamat.setText("Jl. VEteran 3, Malang");
             usia. setText("20 Tahun");
             jk.setText("Perempuan");
             goldar.setText("O");
             status.setText("Belum Menikah");
             negara.setText("Indonesia");
             praktik.setText("Pagi (22.00-06.00)");
             spesialis.setText("Dokter Gigi");  
         }
         else
           if(jconadokt.getSelectedItem().equals("DR. Harun Fajar")){
             nama.setText("DR. Harun Fajar");
             alamat.setText("Jl. Bandung 9, Malang");
             usia. setText("20 Tahun");
             jk.setText("Lakii-Laki");
             goldar.setText("B");
             status.setText("Belum Menikah");
             negara.setText("Indonesia");
             praktik.setText("Pagi (22.00-06.00)");
             spesialis.setText("Dokter Gigi");  
         }
    }//GEN-LAST:event_jconadoktActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemilihandokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemilihandokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemilihandokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemilihandokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemilihandokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField goldar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jk;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField negara;
    private javax.swing.JTextField praktik;
    private javax.swing.JTextField spesialis;
    private javax.swing.JTextField status;
    private javax.swing.JTextField usia;
    // End of variables declaration//GEN-END:variables
}
